name: Build and Release EXE

# トリガー: "v"で始まるタグ（例: v1.0, v1.2.3）がプッシュされたら実行
on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    # Windows環境でビルドを実行
    runs-on: windows-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. PyInstallerで実行ファイルをビルド
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed --name "Notion-File-Transfer" main.py

      # 5. リリースを作成し、ビルドしたEXEファイルを添付
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # `dist`フォルダ内のexeファイルをリリースに添付
          files: dist/Notion-File-Transfer.exe