name: Build and Release EXE

# トリガー: "v"で始まるタグ（例: v1.0, v1.2.3）がプッシュされたら実行
on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    # Windows環境でビルドを実行
    runs-on: windows-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 依存関係インストール + PyInstallerブートローダー再構築
      - name: Install dependencies and build PyInstaller from source
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
          git clone https://github.com/pyinstaller/pyinstaller.git
          cd pyinstaller/bootloader
          python ./waf distclean all
          cd ..
          pip install .

      # 4. PyInstallerで.exeファイルをビルド（クリーン・UPX無効化）
      - name: Build executable
        run: pyinstaller --onefile --windowed --name "Notion-File-Transfer" main.py

      # 5. リリースを更新し、EXEファイルとノートを添付
      - name: Update Release with EXE and Notes
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: ./dist/Notion-File-Transfer.exe
